### PR TITLE
Fixes & clean-ups

### PR DESCRIPTION
**Pull request by piranna**

### CODE REVIEW

**Comment by piranna** [comment]
With Node.js 10 tests are now passing, but with latests version is still spinning. It happens the same in my laptop.

**Comment by maugenst** [comment]
The problem with the local spawned mock server is that it does not terminate on node 13 ... So I'm currently searching for alternatives as this doesn't work out also on my local node13... I didn't expect since it succeeded on node12. Sorry, my fault. :-(

**Comment by piranna** [comment]
> The problem with the local spawned mock server is that it does not terminate on node 13 ... So I'm currently searching for alternatives as this doesn't work out also on my local node13... I didn't expect since it succeeded on node12. Sorry, my fault. :-(

What about using [nock](https://github.com/nock/nock)?

**Comment by maugenst** [comment]
> > The problem with the local spawned mock server is that it does not terminate on node 13 ... So I'm currently searching for alternatives as this doesn't work out also on my local node13... I didn't expect since it succeeded on node12. Sorry, my fault. :-(
> 
> What about using [nock](https://github.com/nock/nock)?

Looks very promising but still the runtime is not returning. It seems to be a general issue:

**Comment by piranna** [comment]
Thank you :-)

**Pull request merged**
