### PR TITLE
Add request library in dependencies list

### PR DESCRIPTION
**Pull request by joaobarbosa**
Add `request` as a direct dependency again, as it's required in the [AbstractToJson](https://github.com/maugenst/tabletojson/blob/master/lib/AbstractToJson.js#L3) file, avoiding `MODULE NOT FOUND` errors.

Example:

```js
// before:
// $ npm install tabletojson
// `requests` was not installed

const tabletojson = require('tabletojson');

// some code...
```
results in:
```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'request'
Require stack:
- /path/to/project/node_modules/tabletojson/lib/AbstractToJson.js
- /path/to/project/node_modules/tabletojson/lib/tabletojson.js
- /path/to/project/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/path/to/project/node_modules/tabletojson/lib/AbstractToJson.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/path/to/project/node_modules/tabletojson/lib/tabletojson.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path/to/project/node_modules/tabletojson/lib/AbstractToJson.js',
    '/path/to/project/node_modules/tabletojson/lib/tabletojson.js',
    '/path/to/project/index.js'
  ]
```

### CODE REVIEW

**Comment by maugenst** [comment]
Perfect ... solves this error ...

Nonetheless I think I'm going to replace it by some other request replacement. But thanks anyway!!!

**Comment by joaobarbosa** [comment]
> Nonetheless I think I'm going to replace it by some other request replacement. But thanks anyway!!!

I thought about it since `request` is not going to being actively developed anymore, but decided to leave the replacement decision to you, @maugenst 👍

**Comment by joaobarbosa** [comment]
@maugenst I forgot to update the `package-lock` with the current version (`1.2.1`) 🤦‍♂ Could you do that or do you want me to open another PR?

**Comment by maugenst** [comment]
@joaobarbosa  ... I recently published a new version which is a total rewrite in ts. This also includes the usage of got instead of request. Please have a look on it and feel free to send me some remarks or suggestions.

BR :-)

**Pull request merged**
