### PR TITLE
Respect cells `rowspan` attribute

### PR DESCRIPTION
**Pull request by piranna**

### CODE REVIEW

**Comment by piranna** [comment]
Thank you! :-) When could this be published to npm?

**Comment by maugenst** [comment]
Hi Jesus...

I bumped the version to 1.1.1 and published it to npm. I also added a few tests to cover the rowspan feature. Please have a look ...

CU, Marius

**Comment by piranna** [comment]
Great, thank you! :-D I've review the tests and look good to me :-)

**Comment by maugenst** [comment]
Cool :-) 

I recently thought about implementing complex rowspans like this:
`// Table
| PARENT | CHILD | AGE |
+--------+-------+-----+
|        |   Sue |  15 |
+        +-------+-----+
| Marry  | Steve |  12 |
+        +-------+-----+
|        |       |     |
+--------+   Tom |   3 +
|        |       |     |
+ Taylor +-------+-----+
|        | Peter |  17 |
+--------+-------+-----+

// Example output
[{
  PARENT: 'Marry', CHILD: 'Sue', AGE, '15'
  PARENT: 'Marry', CHILD: 'Steve', AGE, '12',
  PARENT: 'Marry', CHILD: 'Tom', AGE, '3',
  PARENT: 'Taylor', CHILD: 'Tom', AGE, '3',
  PARENT: 'Taylor', CHILD: 'Peter', AGE, '17'
}]`

Do you have an idea on how to proceed here? I think the current implementation is feasible for rowspans on the first column and works fine. But now I think that we should rework it a bit. What do you think?

I opened a separate branch that you can have a look on: **complexRowspans**

**Comment by maugenst** [comment]
Opened an Issue to not forget this ... [Issue44](https://github.com/maugenst/tabletojson/issues/44)

**Comment by piranna** [comment]
I think my code should work for that complex rowspans too, I'm storing an index of the current active rowspans in the [rowspans](https://github.com/maugenst/tabletojson/pull/43/files#diff-4657c6d2fc7762fb0631570e5fccb099R105) variable, it's as simple as adding a test for comples rowspans and see if it pass :-)

**Comment by maugenst** [comment]
I tested it, but it doesn't work ... :-( 
It would be nice if you can have a look on it since it is your "baby" :-) ...

You can use the above mentioned branch...

**Comment by piranna** [comment]
> You can use the above mentioned branch...

Fixed in #45

**Pull request merged**
