### PR TITLE
Allow `td` nodes with `useFirstRowForHeadings`

### PR DESCRIPTION
**Pull request by piranna**
First row don't need to use canonical `th` nodes to mark headers. Found at https://wiki.ubuntu.com/Releases

### CODE REVIEW

**Comment by piranna** [comment]
Fixed, It has a typo. I've also updated eslint dependencies.

**Comment by maugenst** [comment]
Please also update the package-lock.json here...

**Comment by piranna** [comment]
> Please also update the package-lock.json here...

Done :-)

**Comment by piranna** [comment]
Thanks! :-D

**Pull request merged**
